apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-production

resources:
  - ../../base
  - namespace.yml

patches:
  - path: patch-deployment.yml

images:
  - name: bosssawit/devops
    newTag: 1.0.0
