apiVersion: v1
kind: ConfigMap

metadata:
  name: devops-config

data:
  APP_NAME: "Laravel"

  APP_ENV: "local"
  APP_DEBUG: "true"

  APP_URL: "http://localhost"

  DB_CONNECTION: "pgsql"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_DATABASE: "devops"

  SESSION_DRIVER: "database"

  FILESYSTEM_DISK: "local"

  MAIL_MAILER: "smtp"
  MAIL_HOST: "sandbox.smtp.mailtrap.io"
  MAIL_PORT: "2525"
  MAIL_FROM_ADDRESS: "noreply@designplus.com"
  MAIL_FROM_NAME: "Laravel"

  GOOGLE_REDIRECT_URI: "http://127.0.0.1:8000/auth/google/callback"
  GOOGLE_CLIENT_ID: "174565405616-8tefkupe20uhuegqk9m5h3tt90ga46an.apps.googleusercontent.com"
