apiVersion: v1
kind: Secret

metadata:
  name: devops-secret
type: Opaque

stringData:
  APP_KEY: "base64:gfnSztds1KekqjroOM3JVs5mOY4EU+VbAS76a0EPtVQ="

  stringData:
  POSTGRES_USER: root
  POSTGRES_PASSWORD: ""
  POSTGRES_DB: designplus_db

  JWT_SECRET: "super_secret_key_32_characters_long!!"

  MAIL_USERNAME: "baa6ef3ddcd3ae"
  MAIL_PASSWORD: "0443ea5c79c63c"

  GOOGLE_CLIENT_SECRET: "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"

  XENDIT_SECRET_KEY: "xnd_development_DxcBh8o6xdE5x7aWa6KhIdDe31KSgwxzUnogNwPnqZ0c5qkJ6Gk16wC1vJLSDNTv"
