apiVersion: v1
kind: Secret

metadata:
  name: devops-secret
type: Opaque

stringData:
  APP_KEY: "base64:laravel-app-key="

  stringData:
  POSTGRES_USER: root
  POSTGRES_PASSWORD: ""
  POSTGRES_DB: designplus_db

  JWT_SECRET: "super_secret_key_32_characters_long!!"

  MAIL_USERNAME: "asdasndasuda"
  MAIL_PASSWORD: "913nobdasyduba"

  GOOGLE_CLIENT_SECRET: "GOOGLE-SECRET"

  XENDIT_SECRET_KEY: "xendit_secret-key"
